# Generated by Django 5.2.4 on 2025-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contactinfo_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
